### ISSUE TITLE
Collection-Type DTO fields initialization with null instead of emtpyXxx

### ISSUE THREAD

**Issue by timmo** [hanack/intellij-generator-plugin#13]
# Current Situation

Fields within the DTO of type "Set" or "List" are initialized with null.
 private java.util.Set<Person> family;
# Target Situation

Fields are initialized with Collections.emptySet / List.
# Enhancement

Dtos contains "add" and "remove" methods for collections. Initialization should then as with "new ArrayList<T>()" or "new HashSet<T>()"

**Comment by hanack** [comment]
Enhancement is realized via configuration of variable initializer. 
Simple mechanism to respect generics implemented.
